### ISSUE TITLE
install.sh reports /usr/local/bin not in PATH incorrectly:

### ISSUE THREAD

**Issue by jhheider** [teaxyz/setup#100] opened 2022-12-06 18:33 UTC
```sh
docker pull ubuntu
docker run -it ubuntu /bin/bash
apt update
apt install -y curl
sh <(curl tea.xyz)
...
  │ hmmm, sudo command not found.
  │ try installing sudo


  │ hmmm,  /usr/local/bin  isn’t in your path,
  │ you’ll need to fix that yourself.
  │ sorry 😞
...
echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by mxcl** [comment] 2022-12-11 13:33
Dupe of #51

**Closed by mxcl** 2022-12-11 13:33 UTC
